### ISSUE TITLE
Alerts.addAllAsFriends return type error

### ISSUE THREAD

**Issue by kmntree** [qrtt1/jplurk-oauth#12]
https://www.plurk.com/API#/APP/Alerts/addAllAsFriends

/APP/Alerts/addAllAsFriends

Successful return:
{"success_text": "ok"}

But in Alerts.java, method return type is JSONArray and use thenJsonArray() to parse result.
This bug will make addAllAsFriends() always throw Exception.

**Comment by qrtt1** [comment]
thanks for the report. we fixed it https://github.com/qrtt1/jplurk-oauth/commit/a3701c85cdfb16af43ddfe35ba38cd7daa322004
