### ISSUE TITLE
New Qualifier

### ISSUE THREAD

**Issue by kmntree** [qrtt1/jplurk-oauth#15]
There are few new qualifiers in Plurk:
買(buys)、賣(sells)、吃(eats)

Maybe you can let fromString() return Qualifiers.NULL as a default case?

**Comment by qrtt1** [comment]
It is a good idea to handle this situation. https://github.com/qrtt1/jplurk-oauth/commit/77522c5b8bee964bbcf4bd914fdf466cdb1ee0d9

However, it is still a work-around for our library. I am going to ask plurk-api to provide a regular way having a up-to-date qualifier list.
