### ISSUE TITLE
Real time notifications

### ISSUE THREAD

**Issue by kmntree** [qrtt1/jplurk-oauth#16]
1. `Realtime.cometUserChannel()`

Use `Realtime.cometUserChannel()` to get data from plurk https comet server (`https://comet02.plurk.com/comet`, which `/APP/Realtime/getUserChannel` returns) will get:
`com.google.jplurk_oauth.skeleton.RequestException: org.scribe.exceptions.OAuthException: Problems while creating connection`

If I change comet server URL from "https" to "http",
no more connection problems occur, 
but always get weird `{"new_offset": -1}` even if I reponsed to that timeline.

2. `getUserChannel(String channel)` & `getUserChannel(String channel, Args optional)`

These two methods always return the same response as `getUserChannel()`.
It seems like `channel` and `offset` is the GET params of comet_server URL, 
like `https://comet02.plurk.com/comet?channel=xxxxxxxxx&offset=0`,
not for the `/APP/Realtime/getUserChannel` API.

I'm a newer of comet channel. 
So there may be some problems in my words.

**Comment by qrtt1** [comment]
Well, I haven't use it :) If you could PR it, I would appreciated. 

By the way, it is possible to show problem either English or Chinese. (I know them)

**Comment by kmntree** [comment]
好喔，那我試著研究看看，謝謝您的幫助：）

**Comment by kmntree** [comment]
您好，我稍微測試了一下，獲得了初步成果：

使用`/APP/Realtime/getUserChannel`可以獲得comet_server URL，
如`https://comet02.plurk.com/comet?channel=<channel_name>`。
我使用Postman此API測試工具，直接對獲得的URL做GET可以拿到資料。
（不過好像在清空未讀訊息之前都抓不到新回應/新噗... 不太確定... ← 待測行為）

對comet_server URL做GET是不需要帶入任何OAuth相關的參數的，
我想主要的問題還是如何與https comet server做連線，
想請問您在https GET這方面有什麼推薦lib與注意事項嗎？

我用HttpClient 3.1(jplurk-oauth的相依套件)直接去做GET，結果噴出憑證錯誤之類的問題：
`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

但是對噗浪API的呼叫是用https、上傳圖片給噗浪API也是使用HttpClient，
我不太確定直接GET https URL的問題是出在哪裡... 
如果您有什麼想法的話麻煩還請指點，謝謝：）

**Comment by qrtt1** [comment]
我們用的 HttpClient 版本有點舊，在某些時間會有問題。不過看了一下 server 的設定，也許 plurk 需要先幫我們搞定 ssl 設定問題，一來是這樣弄不太安全，而它的 cert chain 是壞的。

https://www.ssllabs.com/ssltest/analyze.html?d=comet02.plurk.com

![image](https://user-images.githubusercontent.com/193223/31801699-81c00772-b50f-11e7-8063-55aa87467f45.png)

**Comment by kmntree** [comment]
我有個做噗浪APP的朋友是說，
他在抓comet channel之前，
有先設定好本機端的SSL憑證，
不過我還沒時間研究跟測試。

不過明明在同一台上用jplurk-oauth，
對噗浪API(`https://www.plurk.com`)的https OAuth呼叫都是正確的，
兩者之間應該還有什麼差異是我沒搞懂的 ：｜

如果有後續成果再來報告。

**Comment by qrtt1** [comment]
這應該要回報給 plurk 讓他們修正才是對的呦。因為是他們的 server 沒有正確設定 https 憑證。

**Comment by kmntree** [comment]
喔喔，我看到您在comment上更新的內容了。
那看來目前我們沒有什麼可以做的了 XD

我有直接把comet channel URL改成http去連過(使用Postman)，
用http可以連線，但是當用https能吐資料回來時，
用http永遠都回傳：`CometChannel.scriptCallback({"new_offset": -1});`，
所以用這種做法繞過去也拿不到資料 XD

做噗浪APP的朋友是說「憑證我記得我也去存網頁的來用」，
這樣我猜是他自己想辦法硬hack，吧。我再跟他問看看。

非常感謝您願意花時間幫忙研究與回報，我因此學到了很多。
也謝謝您開發jplurk-oauth，一直以來提供了很多幫助：）

**Comment by qrtt1** [comment]
@kmntree 有新進展了 :D

![image](https://user-images.githubusercontent.com/193223/31805050-751373d8-b523-11e7-8880-1f24526f3774.png)

**Comment by kmntree** [comment]
好快，我再找時間試看看：Ｄ

我剛剛找了一些https憑證原理的文章，
總算比較搞懂這技術在幹嘛了 XDDD

感謝您的協助，有進度的話我再過來回報。

**Comment by kmntree** [comment]
已發PR，#17。

在噗浪修正憑證之後，
原本的lib就能正常連線與要到資料了。

所以我只有把不必要的method做移除，
然後寫個CometExample而已。



以下結論：
1. 透過`/APP/Realtime/getUserChannel`可以跟噗浪要到comet server URL，
對此URL進行GET request就能拿到新噗/新回應。

2. `channel`與`offset`是comet server URL的GET參數，而非API的。
沒給`offset`參數也沒關係，因為comet都只會吐Long Polling過程中的新訊息。

3. Comet channel吐訊息感覺很不穩，而且似乎跟網頁上的未讀訊息有關，
有時候把所有未讀訊息給已讀後，channel才會有新回應。
把未讀訊息給已讀，channel會收到此訊息(噗浪API文件沒有)：
`CometChannel.scriptCallback({"new_offset": 1,"data": [{"counts":{"req":0,"noti":91},"type":"update_notification"}]});`

**Comment by kmntree** [comment]
PR #17 爆炸了... XD
可能要麻煩您再花時間指點一下... <(_　_)>

**Comment by qrtt1** [comment]
看起來沒有問題，merge 後也沒事。覺得是 ci 本身環境有 bug。
不過，對於 notification 怎麼使用，還得找時間測試一下，才知道你目前的觀察是不是一致。
